# Jetty
application.name=fpoversikt
context.path=/fpoversikt

brreg.direct.url= https://data.brreg.no/enhetsregisteret

kafka.topic.journal.hendelse=teamdokumenthandtering.aapen-dok-journalfoering

kafka.topic.minside.brukervarsel=min-side.aapen-brukervarsel-v1
