apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fpoversikt-alerts
  labels:
    team: teamforeldrepenger
    app: fpoversikt
  namespace: teamforeldrepenger
spec:
  groups:
    - name:  fpoversikt-alerts
      rules:
        - alert: Mange error på kort tid
          expr: sum by (app) (floor(increase(log_messages_errors{app="fpoversikt", namespace="teamforeldrepenger"}[10m]))) > 2
          annotations:
            consequence: "Flere error er observert i {{ $labels.app }}!"
            action: "Sjekk loggen for {{ $labels.app }} mer info"
          labels:
            severity: critical
        - alert: Ingen poder oppe og tilgjengelig
          expr: sum(up{app="fpoversikt"}) == 0
          for: 10s
          annotations:
            consequence:  "Ingen tilgjengelige podder for FPOVERSIKT"
            action: "Sjekk hvorfor ingen podder er tilgjengelig"
          labels:
            severity: critical
