apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fpoversikt-alerts
  labels:
    team: teamforeldrepenger
    app: fpoversikt
  namespace: teamforeldrepenger
spec:
  groups:
    - name:  fpoversikt-alerts
      rules:
        - alert: Mange error på kort tid
          expr: sum by (app) (floor(increase(log_messages_errors{app="fpoversikt", namespace="teamforeldrepenger"}[10m]))) > 2
          annotations:
            consequence: "Flere error er observert i {{ $labels.app }}!"
            action: "Sjekk loggen for {{ $labels.app }} mer info"
          labels:
            severity: critical
        - alert: Ingen poder oppe og tilgjengelig
          expr: sum(up{app="fpoversikt"}) == 0
          for: 10s
          annotations:
            consequence:  "Ingen tilgjengelige podder for FPOVERSIKT"
            action: "TODO"
          labels:
            severity: critical
        - alert: Mange 4xx feil på kort tid
          expr: sum by (app, namespace) (increase(http_client_requests_seconds_count{namespace="fpsak", status=~"^4.."}[1m]) > 5)
          annotations:
            consequence: "Opplever mange 4xx feil mot fpoversikt på kort tid"
            action: "Sjekk loggen for {{ $labels.app }} mer info"
          labels:
            severity: critical
