kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{namespace}}
spec:
  image: {{image}}
  port: 8080
  {{#if ingress}}
  ingresses:
    - {{ingress}}
  {{/if}}
  liveness:
    path: /fpoversikt/internal/health/isAlive
    initialDelay: 15
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  readiness:
    path: /fpoversikt/internal/health/isReady
    initialDelay: 15
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  prometheus:
    enabled: true
    path: /fpoversikt/internal/metrics/prometheus
  preStopHook:
    http:
      path: /fpoversikt/internal/health/preStop
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 80
  resources:
    limits:
      cpu: "{{limits.cpu}}"
      memory: "{{limits.mem}}"
    requests:
      cpu: "{{requests.cpu}}"
      memory: "{{requests.mem}}"
  kafka:
    pool: {{kafkaPool}}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: fpoversikt
        tier: {{dbTier}}
        diskAutoresize: {{dbDiskAutoresize}}
        highAvailability: {{dbHighAvailability}}
        pointInTimeRecovery: {{dbPointInTimeRecovery}}
        collation: nb_NO.UTF8
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "azp_name"
        groups:
          {{#each groups as |group|}}
             - id: "{{group.uuid}}"
         {{/each}}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
        - id: secure_logs
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: engangsstonad
        - application: foreldrepengeoversikt
        - application: foreldrepengesoknad
        - application: svangerskapspengesoknad
        - application: planlegger
        - application: veiviser-fp-eller-es
        - application: veiviser-hvor-mye
        {{#if azure-token-generator}}
        - application: azure-token-generator
          namespace: nais
        {{/if}}
        - application: fp-swagger
          namespace: teamforeldrepenger
          cluster: {{environment}}-gcp
          permissions:
            scopes:
              - swagger
    outbound:
      rules:
        - application: digdir-krr-proxy
          namespace: team-rocket
        - application: sokos-kontoregister-person
          namespace: okonomi
      external:
        - host: pdl-api.{{environment}}-fss-pub.nais.io
        - host: aareg-services.{{environment}}-fss-pub.nais.io
        - host: ereg-services.{{environment}}-fss-pub.nais.io
        - host: fpsak-api.{{environment}}-fss-pub.nais.io
        - host: fptilbake.{{environment}}-fss-pub.nais.io
        - host: saf.{{environment}}-fss-pub.nais.io
        - host: safselvbetjening.{{environment}}-fss-pub.nais.io
