CREATE TABLE BEREGNINGER
(
    ID                        NUMERIC,
    SAKSNUMMER                VARCHAR(50) UNIQUE,
    JSON                      JSONB
);
ALTER TABLE BEREGNINGER ADD CONSTRAINT PK_BEREGNINGER PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_BEREGNINGER MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NO CYCLE;


