CREATE TABLE SAK
(
    ID                        NUMERIC,
    SAKSNUMMER                VARCHAR(50) UNIQUE,
    JSON                      JSONB
);
ALTER TABLE SAK ADD CONSTRAINT PK_SAK PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_SAK MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NO CYCLE;

CREATE INDEX IDX_AKTOER_INDEX ON SAK USING HASH ((json->>'aktørId'));


