CREATE TABLE ANNEN_PART_UTTAKSPLAN
(
    ID          NUMERIC     NOT NULL,
    SAKSNUMMER  VARCHAR(50) NOT NULL,
    JSON        JSONB       NOT NULL,
    CONSTRAINT PK_ANNEN_PART_UTTAKSPLAN PRIMARY KEY (ID),
    CONSTRAINT UIDX_ANNEN_PART_UTTAKSPLAN_SAKSNUMMER UNIQUE (SAKSNUMMER)
);

CREATE SEQUENCE SEQ_ANNEN_PART_UTTAKSPLAN MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NO CYCLE;

COMMENT ON TABLE ANNEN_PART_UTTAKSPLAN IS 'Inneholder innsendt uttaksplan for norsk annen part';
COMMENT ON COLUMN ANNEN_PART_UTTAKSPLAN.SAKSNUMMER IS 'Saksnummer til søkers sak';
COMMENT ON COLUMN ANNEN_PART_UTTAKSPLAN.JSON IS 'Inneholder mottatt tidspunkt og perioder for annen part';
