CREATE TABLE OPPGAVE
(
    ID                        UUID,
    SAKSNUMMER                VARCHAR(50) UNIQUE,
    TYPE                      VARCHAR(100) NOT NULL,
    STATUS                    VARCHAR(100) NOT NULL,
    OPPRETTET_TID             TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL DEFAULT LOCALTIMESTAMP,
    ENDRET_TID                TIMESTAMP(3) WITHOUT TIME ZONE
);
ALTER TABLE OPPGAVE ADD CONSTRAINT PK_OPPGAVE PRIMARY KEY (ID);
