CREATE TABLE INNTEKTSMELDINGER
(
    ID                        NUMERIC,
    SAKSNUMMER                VARCHAR(50) UNIQUE,
    JSON                      JSONB
);
ALTER TABLE INNTEKTSMELDINGER ADD CONSTRAINT PK_INNTEKTSMELDINGER PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_INNTEKTSMELDINGER MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NO CYCLE;


