CREATE TABLE BEREGNING
(
    ID                        NUMERIC,
    SAKSNUMMER                VARCHAR(50) UNIQUE,
    JSON                      JSONB
);
ALTER TABLE BEREGNING ADD CONSTRAINT PK_BEREGNING PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_BEREGNING MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NO CYCLE;


