CREATE TABLE MANGLENDE_VEDLEGG
(
    ID                        NUMERIC,
    SAKSNUMMER                VARCHAR(50) UNIQUE,
    JSON                      JSONB
);
ALTER TABLE MANGLENDE_VEDLEGG ADD CONSTRAINT PK_MANGLENDE_VEDLEGG PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_MANGLENDE_VEDLEGG MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NO CYCLE;


