CREATE TABLE VEDTAK
(
    ID                        NUMERIC,
    JSON                      JSONB
);
ALTER TABLE VEDTAK ADD CONSTRAINT PK_VEDTAK PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_VEDTAK MINVALUE 1000000 START WITH 1000000 INCREMENT BY 50 NO CYCLE;

CREATE INDEX idxgin ON VEDTAK USING GIN (JSON);
