name: Bygg og deploy
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - '.editorconfig'
      - '.java-version'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.github/dependabot.yml'

jobs:
  build-app:
    name: Build
    uses: navikt/fp-gha-workflows/.github/workflows/build-app-postgres.yml@main
    with:
      postgres-user: fpoversikt
      sonar-scan: true
      build-image: ${{ github.ref_name == 'master' }} # default: true
      push-image: ${{ github.ref_name == 'master' }} # default: false
    secrets: inherit

  deploy-dev:
    name: Deploy dev
    if: github.ref_name == 'master'
    needs: build-app
    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
    with:
      image: ghcr.io/${{ github.repository }}:${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
    secrets: inherit
